apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-cluster-admin
  namespace: buildx
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: sa-cluster-admin-role
  namespace: buildx
subjects:
  - kind: ServiceAccount
    name: buildx
roleRef:
  kind: Role
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io