apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-cluster-admin
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: sa-cluster-admin-role
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io